package com.ytx.mapper;

import java.util.List;

import com.ytx.pojo.Classhours;

public interface ClasshoursMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int insert(Classhours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *	添加课时
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int insertSelective(Classhours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    Classhours selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int updateByPrimaryKeySelective(Classhours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int updateByPrimaryKey(Classhours record);
    
    /**
     * 根据学生id查询对应的课时
     * @param id
     * @return
     */
    List<Classhours> hourslist(Long studentid);
    
}