package com.ytx.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ytx.pojo.Classhours;

public interface ClasshoursMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int insert(Classhours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *	添加课时
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int insertSelective(Classhours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    Classhours selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int updateByPrimaryKeySelective(Classhours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classhours
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int updateByPrimaryKey(Classhours record);
    
    /**
     * 根据学生id查询对应的课时
     * @param id
     * @return
     */
    List<Classhours> hourslist(Long studentid);
    
    /**
     * 根据老师id查询上课情况
     * @param studentid
     * @return
     */
    List<Classhours> teahourslist(Long teacherid);
    
    /**
     * 审核课程
     * @param classhours
     * @return
     */
    List<Classhours> teahourssh(Long teacherid);
    
    /**
     * 通过或不通过审核课程
     * @param classhoursid
     * @return
     */
    int ident(@Param("classhoursid")Long classhoursid,@Param("status")Integer status);
    
    /**
     * 根据学生id删除课时
     * @param studentid
     * @return
     */
    Integer delClasshoursfindstudentid(@Param("studentid")Long studentid,@Param("teacherid")Long teacherid);
    
    
}