package com.ytx.mapper;

import com.ytx.pojo.Sch;

public interface SchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sch
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sch
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int insert(Sch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sch
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int insertSelective(Sch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sch
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    Sch selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sch
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int updateByPrimaryKeySelective(Sch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sch
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int updateByPrimaryKey(Sch record);
    
    /**
     * 校长登录
     * @param sch
     * @return
     */
    Sch schone(Sch sch);
}