package com.ytx.mapper;

import java.util.List;

import com.ytx.pojo.Subject;

public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int insertSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    Subject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sun Jul 12 23:13:43 CST 2020
     */
    int updateByPrimaryKey(Subject record);
    
    /**
     * 查询所有科目名称
     * @return
     */
    List<Subject> subjectLists(Long majorid);
}