package com.ytx.pojo;

import java.util.Date;

public class Classhours {
	
	//科目名称
	private String subjectname;
	//姓名
	private String studentname;
	//上课老师
	private String teachername;
	
	

	public String getSubjectname() {
		return subjectname;
	}

	public void setSubjectname(String subjectname) {
		this.subjectname = subjectname;
	}

	public String getStudentname() {
		return studentname;
	}

	public void setStudentname(String studentname) {
		this.studentname = studentname;
	}

	public String getTeachername() {
		return teachername;
	}

	public void setTeachername(String teachername) {
		this.teachername = teachername;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classhours.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classhours.subjectid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long subjectid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classhours.studentid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long studentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classhours.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Date modifydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classhours.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long modifyby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classhours.ident
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long ident;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classhours.message
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String message;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classhours.coursedate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Date coursedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classhours.teacherid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long teacherid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classhours.id
	 * @return  the value of classhours.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classhours.id
	 * @param id  the value for classhours.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classhours.subjectid
	 * @return  the value of classhours.subjectid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getSubjectid() {
		return subjectid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classhours.subjectid
	 * @param subjectid  the value for classhours.subjectid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setSubjectid(Long subjectid) {
		this.subjectid = subjectid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classhours.studentid
	 * @return  the value of classhours.studentid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getStudentid() {
		return studentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classhours.studentid
	 * @param studentid  the value for classhours.studentid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setStudentid(Long studentid) {
		this.studentid = studentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classhours.modifydate
	 * @return  the value of classhours.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classhours.modifydate
	 * @param modifydate  the value for classhours.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classhours.modifyby
	 * @return  the value of classhours.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getModifyby() {
		return modifyby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classhours.modifyby
	 * @param modifyby  the value for classhours.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setModifyby(Long modifyby) {
		this.modifyby = modifyby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classhours.ident
	 * @return  the value of classhours.ident
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getIdent() {
		return ident;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classhours.ident
	 * @param ident  the value for classhours.ident
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setIdent(Long ident) {
		this.ident = ident;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classhours.message
	 * @return  the value of classhours.message
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classhours.message
	 * @param message  the value for classhours.message
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setMessage(String message) {
		this.message = message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classhours.coursedate
	 * @return  the value of classhours.coursedate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Date getCoursedate() {
		return coursedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classhours.coursedate
	 * @param coursedate  the value for classhours.coursedate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setCoursedate(Date coursedate) {
		this.coursedate = coursedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classhours.teacherid
	 * @return  the value of classhours.teacherid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getTeacherid() {
		return teacherid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classhours.teacherid
	 * @param teacherid  the value for classhours.teacherid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setTeacherid(Long teacherid) {
		this.teacherid = teacherid;
	}
}