package com.ytx.pojo;

import java.util.Date;

public class Class {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.teacherid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long teacherid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.classdesc
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String classdesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Date modifydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long modifyby;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.id
	 * @return  the value of class.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.id
	 * @param id  the value for class.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.name
	 * @return  the value of class.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.name
	 * @param name  the value for class.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.teacherid
	 * @return  the value of class.teacherid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getTeacherid() {
		return teacherid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.teacherid
	 * @param teacherid  the value for class.teacherid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setTeacherid(Long teacherid) {
		this.teacherid = teacherid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.classdesc
	 * @return  the value of class.classdesc
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getClassdesc() {
		return classdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.classdesc
	 * @param classdesc  the value for class.classdesc
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setClassdesc(String classdesc) {
		this.classdesc = classdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.modifydate
	 * @return  the value of class.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.modifydate
	 * @param modifydate  the value for class.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.modifyby
	 * @return  the value of class.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getModifyby() {
		return modifyby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.modifyby
	 * @param modifyby  the value for class.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setModifyby(Long modifyby) {
		this.modifyby = modifyby;
	}
}