package com.ytx.pojo;

import java.util.Date;

public class Major {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Date modifydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long modifyby;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major.id
	 * @return  the value of major.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major.id
	 * @param id  the value for major.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major.name
	 * @return  the value of major.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major.name
	 * @param name  the value for major.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major.modifydate
	 * @return  the value of major.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major.modifydate
	 * @param modifydate  the value for major.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major.modifyby
	 * @return  the value of major.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getModifyby() {
		return modifyby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major.modifyby
	 * @param modifyby  the value for major.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setModifyby(Long modifyby) {
		this.modifyby = modifyby;
	}
}