package com.ytx.pojo;

public class Sch {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sch.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sch.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sch.address
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sch.xzname
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String xzname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sch.xzpwd
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String xzpwd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sch.id
	 * @return  the value of sch.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sch.id
	 * @param id  the value for sch.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sch.name
	 * @return  the value of sch.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sch.name
	 * @param name  the value for sch.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sch.address
	 * @return  the value of sch.address
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sch.address
	 * @param address  the value for sch.address
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sch.xzname
	 * @return  the value of sch.xzname
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getXzname() {
		return xzname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sch.xzname
	 * @param xzname  the value for sch.xzname
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setXzname(String xzname) {
		this.xzname = xzname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sch.xzpwd
	 * @return  the value of sch.xzpwd
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getXzpwd() {
		return xzpwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sch.xzpwd
	 * @param xzpwd  the value for sch.xzpwd
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setXzpwd(String xzpwd) {
		this.xzpwd = xzpwd;
	}
}