package com.ytx.pojo;

import java.util.Date;

public class Subject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column subject.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column subject.subjectname
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String subjectname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column subject.teacherid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long teacherid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column subject.majorid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long majorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column subject.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Date modifydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column subject.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long modifyby;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column subject.id
	 * @return  the value of subject.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column subject.id
	 * @param id  the value for subject.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column subject.subjectname
	 * @return  the value of subject.subjectname
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getSubjectname() {
		return subjectname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column subject.subjectname
	 * @param subjectname  the value for subject.subjectname
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setSubjectname(String subjectname) {
		this.subjectname = subjectname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column subject.teacherid
	 * @return  the value of subject.teacherid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getTeacherid() {
		return teacherid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column subject.teacherid
	 * @param teacherid  the value for subject.teacherid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setTeacherid(Long teacherid) {
		this.teacherid = teacherid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column subject.majorid
	 * @return  the value of subject.majorid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getMajorid() {
		return majorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column subject.majorid
	 * @param majorid  the value for subject.majorid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setMajorid(Long majorid) {
		this.majorid = majorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column subject.modifydate
	 * @return  the value of subject.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column subject.modifydate
	 * @param modifydate  the value for subject.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column subject.modifyby
	 * @return  the value of subject.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getModifyby() {
		return modifyby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column subject.modifyby
	 * @param modifyby  the value for subject.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setModifyby(Long modifyby) {
		this.modifyby = modifyby;
	}
}