package com.ytx.pojo;

import java.util.Date;

public class Teacher {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.teachercode
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String teachercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.teacherpwd
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String teacherpwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.classid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long classid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.phone
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.photo
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String photo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Date modifydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Long modifyby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.sex
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String sex;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.id
	 * @return  the value of teacher.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.id
	 * @param id  the value for teacher.id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.name
	 * @return  the value of teacher.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.name
	 * @param name  the value for teacher.name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.teachercode
	 * @return  the value of teacher.teachercode
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getTeachercode() {
		return teachercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.teachercode
	 * @param teachercode  the value for teacher.teachercode
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setTeachercode(String teachercode) {
		this.teachercode = teachercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.teacherpwd
	 * @return  the value of teacher.teacherpwd
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getTeacherpwd() {
		return teacherpwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.teacherpwd
	 * @param teacherpwd  the value for teacher.teacherpwd
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setTeacherpwd(String teacherpwd) {
		this.teacherpwd = teacherpwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.classid
	 * @return  the value of teacher.classid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getClassid() {
		return classid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.classid
	 * @param classid  the value for teacher.classid
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setClassid(Long classid) {
		this.classid = classid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.phone
	 * @return  the value of teacher.phone
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.phone
	 * @param phone  the value for teacher.phone
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.photo
	 * @return  the value of teacher.photo
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.photo
	 * @param photo  the value for teacher.photo
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setPhoto(String photo) {
		this.photo = photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.modifydate
	 * @return  the value of teacher.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.modifydate
	 * @param modifydate  the value for teacher.modifydate
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.modifyby
	 * @return  the value of teacher.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Long getModifyby() {
		return modifyby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.modifyby
	 * @param modifyby  the value for teacher.modifyby
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setModifyby(Long modifyby) {
		this.modifyby = modifyby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.sex
	 * @return  the value of teacher.sex
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.sex
	 * @param sex  the value for teacher.sex
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}
}