package com.ytx.pojo;

public class ThinkAreas {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column think_areas.area_id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Short areaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column think_areas.parent_id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Short parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column think_areas.area_name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private String areaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column think_areas.area_type
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	private Boolean areaType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column think_areas.area_id
	 * @return  the value of think_areas.area_id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Short getAreaId() {
		return areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column think_areas.area_id
	 * @param areaId  the value for think_areas.area_id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setAreaId(Short areaId) {
		this.areaId = areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column think_areas.parent_id
	 * @return  the value of think_areas.parent_id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Short getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column think_areas.parent_id
	 * @param parentId  the value for think_areas.parent_id
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setParentId(Short parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column think_areas.area_name
	 * @return  the value of think_areas.area_name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column think_areas.area_name
	 * @param areaName  the value for think_areas.area_name
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column think_areas.area_type
	 * @return  the value of think_areas.area_type
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public Boolean getAreaType() {
		return areaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column think_areas.area_type
	 * @param areaType  the value for think_areas.area_type
	 * @mbggenerated  Sun Jul 12 23:13:43 CST 2020
	 */
	public void setAreaType(Boolean areaType) {
		this.areaType = areaType;
	}
}